version = 0.1
[default.deploy.parameters]
stack_name = "sam-nextjs14-lambda"
resolve_s3 = true
s3_prefix = "sam-nextjs14-lambda"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["NextAppStackFunction=536560382233.dkr.ecr.eu-north-1.amazonaws.com/samnextjs14lambdad505bf11/nextappstackfunctione45a3c19repo"]
