version = 0.1

[default.deploy]
[default.deploy.parameters]
stack_name = "rose"
s3_bucket = "test-1234567890qw"
s3_prefix = "rose"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["NextAppStackFunction=536560382233.dkr.ecr.eu-north-1.amazonaws.com/hello"]
disable_rollback = true
resolve_s3 = true
