AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless app to deploy Next.js app to AWS Lambda

Globals:
  Function:
    Timeout: 30

Resources:
  NextAppStackFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 536560382233.dkr.ecr.eu-north-1.amazonaws.com/hello:latest
      Architectures:
        - x86_64
      Events:
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /{proxy+}
            Method: ANY

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

Outputs:
  NextAppStackUrl:
    Description: 'API Gateway endpoint URL for serving the Next.js app'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/'
